# Generated by Django 5.1.7 on 2025-03-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[("Low", "1"), ("Medium", "2"), ("High", "3")],
                default="Medium",
                max_length=20,
            ),
        ),
    ]
