services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: db
    ports:
      - 5432:5432

  web:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db