services:
  db:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
  web:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db